### ISSUE TITLE
Can't install own chart referencing `AzureKeyVaultSecret`

### ISSUE THREAD

**Issue by francky-powerfactors** [SparebankenVest/public-helm-charts#20]
When I install my own chart referencing a `AzureKeyVaultSecret` I always get the following error:

>Error: validation failed: unable to recognize "": no matches for kind "AzureKeyVaultSecret" in version ""

Here is my yaml file referencing the `AzureKeyVaultSecret`:

```
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: orchestrator-keyvault-secret-1
  namespace: orchestrator-chart-test
spec:
  vault:
    name: poc-pipeline-arch-key01
    object:
      name: test-secret-object-name
      type: secret
  output:
    secret:
      name: test
      dataKey: test-key
      type: opaque
```

And here is my info about helm / kubectl:

```
❯ helm version
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Everything works in kubernetes and I can even `kubectl apply -f` my azure-secret.yaml file and it works but installing it with helm always fails.
